/* eslint-disable import/extensions */
/* eslint-disable @next/next/no-img-element */
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import Script from 'next/script'

import { cn } from '@/lib/utils'
import { Media } from '@/payload/payload-types'
import { fetchSetting } from './_api/fetchGlobals'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const rasbern = localFont({
  src: [
    {
      path: '../../../public/fonts/Rasbern-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/Rasbern-Regular.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-rasbern',
})

const grotesk = localFont({
  src: [
    {
      path: '../../../public/fonts/AlteHaasGroteskRegular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/AlteHaasGroteskBold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-grotesk',
})

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  let setting = null
  try {
    setting = await fetchSetting()
  } catch (error: unknown) {
    // Erro silenciosamente ignorado
  }
  const imgFavicon = setting?.favicon as Media | undefined
  return (
    <html lang="en">
      <head>
        {imgFavicon?.url && (
          <link rel="icon" href={imgFavicon.url} type="image/<generated>" sizes="<generated>" />
        )}
        <Script
          id="fb-pixel"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              !function(f,b,e,v,n,t,s)
              {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
              n.callMethod.apply(n,arguments):n.queue.push(arguments)};
              if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
              n.queue=[];t=b.createElement(e);t.async=!0;
              t.src=v;s=b.getElementsByTagName(e)[0];
              s.parentNode.insertBefore(t,s)}(window, document,'script',
              'https://connect.facebook.net/en_US/fbevents.js');
              fbq('init', '952912943539520');
              fbq('track', 'PageView');
              `,
          }}
        />
        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: 'none' }}
            src="https://www.facebook.com/tr?id=952912943539520&ev=PageView&noscript=1"
          />
        </noscript>
      </head>
      <body className={cn('scroll-smooth overflow-x-hidden', rasbern.variable, grotesk.variable)}>
        {children}
      </body>
    </html>
  )
}
